import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { anggotaService, type Anggota } from '@/services/anggota.service';
import { showToast } from '@/lib/toast';

interface AnggotaFormModalProps {
  mode: 'create' | 'edit';
  anggota: Anggota | null;
  onClose: () => void;
  onSuccess: () => void;
}

export function AnggotaFormModal({ mode, anggota, onClose, onSuccess }: AnggotaFormModalProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const [formData, setFormData] = useState({
    noAnggota: mode === 'create' ? '' : '', // Will be auto-generated by backend
    nik: '',
    namaLengkap: '',
    jenisKelamin: 'L',
    tempatLahir: '',
    tanggalLahir: '',
    alamatLengkap: '',
    rt: '',
    rw: '',
    desa: 'Gembol',
    kecamatan: 'Karanganyar',
    kabupaten: 'Ngawi',
    provinsi: 'Jawa Timur',
    kodePos: '',
    noTelepon: '',
    noWhatsapp: '',
    email: '',
    pendidikanTerakhir: '',
    pekerjaan: '',
    namaBank: '',
    nomorRekening: '',
    atasNamaRekening: '',
    statusAnggota: 'aktif',
    tanggalBergabung: new Date().toISOString().split('T')[0],
    keterangan: '',
  });

  useEffect(() => {
    if (mode === 'edit' && anggota) {
      setFormData({
        noAnggota: anggota.noAnggota,
        nik: anggota.nik,
        namaLengkap: anggota.namaLengkap,
        jenisKelamin: anggota.jenisKelamin,
        tempatLahir: anggota.tempatLahir,
        tanggalLahir: anggota.tanggalLahir,
        alamatLengkap: anggota.alamatLengkap,
        rt: anggota.rt,
        rw: anggota.rw,
        desa: anggota.desa,
        kecamatan: anggota.kecamatan,
        kabupaten: anggota.kabupaten,
        provinsi: anggota.provinsi,
        kodePos: anggota.kodePos,
        noTelepon: anggota.noTelepon || '',
        noWhatsapp: anggota.noWhatsapp || '',
        email: anggota.email || '',
        pendidikanTerakhir: anggota.pendidikanTerakhir || '',
        pekerjaan: anggota.pekerjaan || '',
        namaBank: anggota.namaBank || '',
        nomorRekening: anggota.nomorRekening || '',
        atasNamaRekening: anggota.atasNamaRekening || '',
        statusAnggota: anggota.statusAnggota,
        tanggalBergabung: anggota.tanggalBergabung,
        keterangan: anggota.keterangan || '',
      });
    }
  }, [mode, anggota]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      console.log('Submitting anggota data:', formData);
      
      const response = mode === 'create'
        ? await anggotaService.create(formData)
        : await anggotaService.update(anggota!.id, formData);

      console.log('Response received:', response);

      if (response.success) {
        showToast.success(
          mode === 'create' 
            ? 'Data anggota berhasil ditambahkan!' 
            : 'Data anggota berhasil diperbarui!'
        );
        onSuccess();
      } else {
        const errorMsg = response.message || 'Gagal menyimpan data anggota';
        console.error('Create/update failed:', errorMsg, response);
        showToast.error(errorMsg);
        setError(errorMsg);
      }
    } catch (err) {
      console.error('Error in handleSubmit:', err);
      const errorMsg = err instanceof Error 
        ? `Terjadi kesalahan: ${err.message}`
        : 'Terjadi kesalahan saat menyimpan data';
      showToast.error(errorMsg);
      setError(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-secondary-200 px-6 py-4 flex items-center justify-between">
          <h2 className="text-xl font-display font-bold text-secondary-900">
            {mode === 'create' ? 'Tambah Anggota Baru' : 'Edit Data Anggota'}
          </h2>
          <button
            onClick={onClose}
            className="text-secondary-400 hover:text-secondary-600 transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6">
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
              {error}
            </div>
          )}

          <div className="space-y-6">
            {/* Data Pribadi */}
            <div>
              <h3 className="text-lg font-semibold text-secondary-900 mb-4">Data Pribadi</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    No. Anggota <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="noAnggota"
                    value={formData.noAnggota}
                    onChange={handleChange}
                    required
                    className="input"
                    placeholder="KTH-001"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    NIK <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="nik"
                    value={formData.nik}
                    onChange={handleChange}
                    required
                    maxLength={16}
                    pattern="[0-9]{16}"
                    className="input"
                    placeholder="3201234567890123"
                  />
                </div>
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Nama Lengkap <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="namaLengkap"
                    value={formData.namaLengkap}
                    onChange={handleChange}
                    required
                    className="input"
                    placeholder="Masukkan nama lengkap"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Jenis Kelamin <span className="text-red-500">*</span>
                  </label>
                  <select
                    name="jenisKelamin"
                    value={formData.jenisKelamin}
                    onChange={handleChange}
                    required
                    className="input"
                  >
                    <option value="L">Laki-laki</option>
                    <option value="P">Perempuan</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Tempat Lahir <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="tempatLahir"
                    value={formData.tempatLahir}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Tanggal Lahir <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    name="tanggalLahir"
                    value={formData.tanggalLahir}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Tanggal Bergabung <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="date"
                    name="tanggalBergabung"
                    value={formData.tanggalBergabung}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
              </div>
            </div>

            {/* Alamat */}
            <div>
              <h3 className="text-lg font-semibold text-secondary-900 mb-4">Alamat</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Alamat Lengkap <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    name="alamatLengkap"
                    value={formData.alamatLengkap}
                    onChange={handleChange}
                    required
                    rows={2}
                    className="input"
                    placeholder="Jl. Contoh No. 123"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    RT <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="rt"
                    value={formData.rt}
                    onChange={handleChange}
                    required
                    className="input"
                    placeholder="001"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    RW <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="rw"
                    value={formData.rw}
                    onChange={handleChange}
                    required
                    className="input"
                    placeholder="001"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Desa <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="desa"
                    value={formData.desa}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Kecamatan <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="kecamatan"
                    value={formData.kecamatan}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Kabupaten <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="kabupaten"
                    value={formData.kabupaten}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Provinsi <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="provinsi"
                    value={formData.provinsi}
                    onChange={handleChange}
                    required
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Kode Pos <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    name="kodePos"
                    value={formData.kodePos}
                    onChange={handleChange}
                    required
                    className="input"
                    placeholder="41211"
                  />
                </div>
              </div>
            </div>

            {/* Kontak */}
            <div>
              <h3 className="text-lg font-semibold text-secondary-900 mb-4">Kontak</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    No. Telepon
                  </label>
                  <input
                    type="tel"
                    name="noTelepon"
                    value={formData.noTelepon}
                    onChange={handleChange}
                    className="input"
                    placeholder="08123456789"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    No. WhatsApp
                  </label>
                  <input
                    type="tel"
                    name="noWhatsapp"
                    value={formData.noWhatsapp}
                    onChange={handleChange}
                    className="input"
                    placeholder="08123456789"
                  />
                </div>
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    className="input"
                    placeholder="email@example.com"
                  />
                </div>
              </div>
            </div>

            {/* Data Tambahan */}
            <div>
              <h3 className="text-lg font-semibold text-secondary-900 mb-4">Data Tambahan</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Pendidikan Terakhir
                  </label>
                  <select
                    name="pendidikanTerakhir"
                    value={formData.pendidikanTerakhir}
                    onChange={handleChange}
                    className="input"
                  >
                    <option value="">Pilih Pendidikan</option>
                    <option value="SD">SD</option>
                    <option value="SMP">SMP</option>
                    <option value="SMA">SMA</option>
                    <option value="D3">D3</option>
                    <option value="S1">S1</option>
                    <option value="S2">S2</option>
                    <option value="S3">S3</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Pekerjaan
                  </label>
                  <input
                    type="text"
                    name="pekerjaan"
                    value={formData.pekerjaan}
                    onChange={handleChange}
                    className="input"
                    placeholder="Petani"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Nama Bank
                  </label>
                  <input
                    type="text"
                    name="namaBank"
                    value={formData.namaBank}
                    onChange={handleChange}
                    className="input"
                    placeholder="BRI"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Nomor Rekening
                  </label>
                  <input
                    type="text"
                    name="nomorRekening"
                    value={formData.nomorRekening}
                    onChange={handleChange}
                    className="input"
                    placeholder="1234567890"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Atas Nama Rekening
                  </label>
                  <input
                    type="text"
                    name="atasNamaRekening"
                    value={formData.atasNamaRekening}
                    onChange={handleChange}
                    className="input"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Status Anggota <span className="text-red-500">*</span>
                  </label>
                  <select
                    name="statusAnggota"
                    value={formData.statusAnggota}
                    onChange={handleChange}
                    required
                    className="input"
                  >
                    <option value="aktif">Aktif</option>
                    <option value="tidak_aktif">Tidak Aktif</option>
                  </select>
                </div>
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-secondary-700 mb-1">
                    Keterangan
                  </label>
                  <textarea
                    name="keterangan"
                    value={formData.keterangan}
                    onChange={handleChange}
                    rows={3}
                    className="input"
                    placeholder="Catatan tambahan (opsional)"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 mt-6 pt-6 border-t border-secondary-200">
            <Button type="button" variant="outline" onClick={onClose} disabled={loading}>
              Batal
            </Button>
            <Button type="submit" variant="primary" disabled={loading}>
              {loading ? 'Menyimpan...' : mode === 'create' ? 'Tambah Anggota' : 'Simpan Perubahan'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
